### ISSUE TITLE
Can't Launch Bot "Access denied for user 'grabber'@'localhost' (using password: YES" 

### ISSUE THREAD

**Issue by Sharkbutt32** [kogeki/the-scraper#12]
`Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'grabber'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/root/the-scraper/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/root/the-scraper/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/root/the-scraper/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/root/the-scraper/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/root/the-scraper/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/root/the-scraper/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/root/the-scraper/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/root/the-scraper/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/root/the-scraper/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/root/the-scraper/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/root/the-scraper/node_modules/mysql/lib/Connection.js:116:18)
    at Object.<anonymous> (/root/the-scraper/db.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'grabber'@'localhost' (using password: YES)",
  sqlState: '28000',
  fatal: true
}`

![2022-07-18_21-40](https://user-images.githubusercontent.com/109623849/179831298-3a187cca-cd62-4e0b-9822-6bda91f1694d.png)

**Comment by kogeki** [comment]
SVG, you need to match your password in the config file to the password you set when you setup the database.

**Comment by DRoce** [comment]
what is that background mr sharkbutt

**Comment by kogeki** [comment]
> what is that background mr sharkbutt

https://www.reddit.com/r/Animewallpaper/comments/r81jev/arch_linux_ostan_original_3840x2160/

**Comment by DRoce** [comment]
thank u i like anime waifu especially when she has a very funny hoodie referencing tux linux

**Comment by kogeki** [comment]
> thank u i like anime waifu especially when she has a very funny hoodie referencing tux linux 

These are called "OS-Tans". I enjoy them and always make them my wallpapers.
