### ISSUE TITLE
Bot closes

### ISSUE THREAD

**Issue by DRoce** [kogeki/the-scraper#9]
node index.js

runs, whenever I try a command

it errors 

 
throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Query.<anonymous> (/home/kali/the-scraper/index.js:475:20)
    at Query.<anonymous> (/home/kali/the-scraper/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/kali/the-scraper/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/kali/the-scraper/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/kali/the-scraper/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/kali/the-scraper/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/kali/the-scraper/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/kali/the-scraper/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/kali/the-scraper/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/kali/the-scraper/node_modules/mysql/lib/Connection.js:88:28)

![unknown (5)](https://user-images.githubusercontent.com/90403939/178278150-7ee5b767-b127-49e8-85e1-9814727e616b.png)

**Comment by kogeki** [comment]
You probably have an issue with your MySQL configuration. Make sure you are using the updated setup.sql script.

**Comment by DRoce** [comment]
I could not find the issue with my MySQL configuration, and I am using the updated setup.sql script.

**Comment by kogeki** [comment]
Does the bot say "Connected to database" after starting it?

**Comment by DRoce** [comment]
Yep, it does.

**Comment by DRoce** [comment]
i guess no fix ;c
